config/routes.rb
Rails.application.routes.draw do
  resources :chatwills
  resources :messages
  root to: 'messages#index'

end

app/models/chatwill.rb
class Chatwill < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chatwills_controller.rb
class ChatwillsController < ApplicationController
  before_action :set_chatwill, only: [:show, :edit, :update, :destroy]

  # GET /chatwills
  # GET /chatwills.json
  def index
    @chatwills = Chatwill.all
  end

  # GET /chatwills/1
  # GET /chatwills/1.json
  def show
  end

  # GET /chatwills/new
  def new
    @chatwill = Chatwill.new
  end

  # GET /chatwills/1/edit
  def edit
  end

  # POST /chatwills
  # POST /chatwills.json
  def create
    @chatwill = Chatwill.new(chatwill_params)

    respond_to do |format|
      if @chatwill.save
        format.html { redirect_to @chatwill, notice: 'Chatwill was successfully created.' }
        format.json { render :show, status: :created, location: @chatwill }
      else
        format.html { render :new }
        format.json { render json: @chatwill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatwills/1
  # PATCH/PUT /chatwills/1.json
  def update
    respond_to do |format|
      if @chatwill.update(chatwill_params)
        format.html { redirect_to @chatwill, notice: 'Chatwill was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatwill }
      else
        format.html { render :edit }
        format.json { render json: @chatwill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatwills/1
  # DELETE /chatwills/1.json
  def destroy
    @chatwill.destroy
    respond_to do |format|
      format.html { redirect_to chatwills_url, notice: 'Chatwill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatwill
      @chatwill = Chatwill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatwill_params
      params.require(:chatwill).permit(:sentence, :author, :date)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def create
    require 'csv'
    @message = Message.create!(message_params)
  puts '1'
    search_criteria =  { 'ru' => 'сон' }
    options = { :headers    => :first_row,
                :converters => [ :numeric ] }
    puts '2'
    matches = nil
    puts '3'
    CSV.open("/home/valentin/RubymineProjects/cwi2/mueller.csv", "r", options ) do |csv|
      puts '4'
      matches = csv.find_all do |row|
        match = true
        search_criteria.keys.each do |key|
          match = match && ( row[key] == search_criteria[key] )
        end
        match
      end
      puts '5'
      headers = csv.headers
    end
    File.open("/home/valentin/RubymineProjects/cwi2/message.txt","w") do |f|
      f.puts(matches.sort_by { |r| r['sid'] }.first)
      f.puts('6')
      end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatwills_helper.rb
module ChatwillsHelper
end

app/views/chatwills/_form.html.erb
<%= form_for(@chatwill) do |f| %>
  <% if @chatwill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chatwill.errors.count, "error") %> prohibited this chatwill from being saved:</h2>

      <ul>
      <% @chatwill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sentence %><br>
    <%= f.text_field :sentence %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatwills/edit.html.erb
<h1>Editing Chatwill</h1>

<%= render 'form' %>

<%= link_to 'Show', @chatwill %> |
<%= link_to 'Back', chatwills_path %>

app/views/chatwills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chatwills</h1>
<%=a=system("/home/valentin/RubymineProjects/cwi2/tomita","/home/valentin/RubymineProjects/cwi2/config.proto")%>
<% FlickRaw.api_key="6ac1dd4e8e5b8af32c39a3de4db883fc" %>
<% FlickRaw.shared_secret="e119f82e1a1ed58f" %>
<%list1 =flickr.tags.getHotList()%>
<% list   = flickr.photos.search( :tags =>'road,way',:safe_search=>'3',:page=>'1', :sort=>'relevance',:tag_mode=>'all' ) %>
<% list.each do |list| %>
    <img src="https://farm<%=list.farm%>.staticflickr.com/<%=list.server %>/<%=list.id %>_<%=list.secret %>_m.jpg"/>
<% end %>

<div class="chat-container">
  <ul id="chat">
    <%= render @messages %>
  </ul>

  <%= form_for Message.new, remote: true do |f| %>
      <%= f.text_field :content %>
      <%= f.submit "Send" %>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Sentence</th>
      <th>Author</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatwills.each do |chatwill| %>
      <tr>
        <td><%= chatwill.sentence %></td>
        <td><%= chatwill.author %></td>
        <td><%= chatwill.date %></td>
        <td><%= link_to 'Show', chatwill %></td>
        <td><%= link_to 'Edit', edit_chatwill_path(chatwill) %></td>
        <td><%= link_to 'Destroy', chatwill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatwill', new_chatwill_path %>

app/views/chatwills/new.html.erb
<h1>New Chatwill</h1>

<%= render 'form' %>

<%= link_to 'Back', chatwills_path %>

app/views/chatwills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sentence:</strong>
  <%= @chatwill.sentence %>
</p>

<p>
  <strong>Author:</strong>
  <%= @chatwill.author %>
</p>

<p>
  <strong>Date:</strong>
  <%= @chatwill.date %>
</p>

<%= link_to 'Edit', edit_chatwill_path(@chatwill) %> |
<%= link_to 'Back', chatwills_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cwi2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_message.html.erb
<li>
  <span class="created_at"><%= message.created_at.strftime("%H:%M") %></span>
  <%= message.content %>
</li>

app/views/messages/create.js.erb
$("#new_message")[0].reset();

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chatwills</h1>
<%#FIXME почему-то работает только с абсолютными путями%>
<%=a=system("/home/valentin/RubymineProjects/cwi2/tomita","/home/valentin/RubymineProjects/cwi2/config.proto")%>

<%=system("ruby","/home/valentin/RubymineProjects/cwi2/app/rbscripts/open_to_flickr.rb")%>
<% FlickRaw.api_key="6ac1dd4e8e5b8af32c39a3de4db883fc" %>
<% FlickRaw.shared_secret="e119f82e1a1ed58f" %>
<% list1 =flickr.tags.getHotList()%>
<%=@messages.last.content%>
<%#TODO затычка, сюда пойдут переведенные теги%>
<% list   = flickr.photos.search( :tags =>@messages.last.content,:safe_search=>'3',:page=>'1', :sort=>'relevance',:tag_mode=>'all' ) %>
<% list.each do |list| %>
    <img src="https://farm<%=list.farm%>.staticflickr.com/<%=list.server %>/<%=list.id %>_<%=list.secret %>_m.jpg"/>
<% end %>

<div class="chat-container">
  <ul id="chat">
    <%= render @messages %>
  </ul>

  <%= form_for Message.new, remote: true do |f| %>
      <%= f.text_field :content %>
      <%= f.submit "Send" %>
  <% end %>
</div>